---
- name: Add official repo
  yum_repository: name=gitlab-ce description='Gitlab CE' enabled=no baseurl=https://packages.gitlab.com/gitlab/gitlab-ce/el/$releasever/$basearch gpgcheck=no gpgkey=https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey state=present owner=root group=root mode=0644

- name: Install dependencies
  yum: name={{item}} state=present
  with_items:
    - curl
    - openssh-server
    - openssh-clients
    - postfix

- name: Install GitLab version {{gitlab_version}}
  yum: name=gitlab-ce-{{gitlab_version}} state=present enablerepo=gitlab-ce
  when: gitlab_version != 'latest'

- name: Install latest GitLab
  yum: name=gitlab-ce state=latest enablerepo=gitlab-ce
  when: gitlab_version == 'latest'

- name: Enable ssh server
  service: name=sshd state=started enabled=yes

- name: Bootstrap GitLab
  command: gitlab-ctl reconfigure
  args:
    creates: '/var/opt/gitlab/bootstrapped'

- name: Configure GitLab
  template: dest=/etc/gitlab/gitlab.rb src=gitlab.rb.j2 mode=0600
  notify: Restart gitlab
